# Generated by Django 3.1 on 2020-10-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_instructorprofile_participantprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to='seminar.seminar'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='seminars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='seminar.seminar'),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='dropped_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='joined_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
