# Generated by Django 3.1 on 2020-10-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0003_auto_20201001_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='dropped_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.CharField(choices=[('participant', 'participant'), ('participant', 'instructor')], db_index=True, default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='seminar',
            field=models.ForeignKey(choices=[('participant', 'participant'), ('participant', 'instructor')], on_delete=django.db.models.deletion.CASCADE, related_name='user_seminars', to='seminar.seminar'),
        ),
        migrations.AlterField(
            model_name='userseminar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seminars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userseminar',
            unique_together={('user', 'seminar')},
        ),
    ]
