# Generated by Django 3.1 on 2020-10-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='ParticipantProfile',
        ),
    ]
